import SectionHeading from '../components/SectionHeading.jsx'
import { photo } from '../data/products.js'

export default function AboutPage() {
  return (
    <main>
      <section className="mx-auto max-w-[1440px] px-5 pb-14 pt-14 sm:px-8 sm:pb-20 sm:pt-20 lg:px-12"><p className="mb-4 text-[10px] font-semibold uppercase tracking-[.2em] text-[#887963]">The Form & Field story</p><h1 className="serif max-w-[950px] text-[45px] leading-[1.08] sm:text-[68px] lg:text-[78px]">Good things take time.<br /><em className="font-medium text-[var(--forest)]">And they should.</em></h1><p className="mt-7 max-w-[490px] text-[14px] leading-7 text-[#666b62]">We started Form & Field with one simple question: what if the things we bring home made us feel more at home?</p></section>
      <div className="relative h-[340px] sm:h-[520px]"><img src={photo('photo-1616486338812-3dadae4b4ace', 1800)} alt="A welcoming home filled with natural materials and considered design" className="absolute inset-0 size-full object-cover" /></div>
      <section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-16 sm:px-8 sm:py-24 md:grid-cols-[.7fr_1fr] lg:gap-28 lg:px-24"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#887963]">A note from our founder</p><h2 className="serif mt-4 text-[38px] leading-tight sm:text-[48px]">The pieces we keep.</h2></div><div className="space-y-5 text-[14px] leading-7 text-[#62675f]"><p>Somewhere along the way, more became the default. More things, more noise, more to replace. We wanted to make a small space for something different: objects chosen carefully, made thoughtfully, and loved for a long, long time.</p><p>We work with independent makers and small workshops who care as much about the process as the finished piece. Natural materials. Patient hands. No shortcuts that cost the earth or the people who make our things.</p><p>Because a home isn’t made in a day. It’s made slowly, in the little rituals and familiar objects that become part of your story.</p><p className="serif pt-2 text-[21px] text-[var(--ink)]">With care, <br />Mara & the Form & Field team</p></div></section>
      <section className="bg-[#e8e7de] px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-[1160px]"><SectionHeading eyebrow="What we believe" title="A few things we hold close." /><div className="grid gap-8 sm:grid-cols-3 sm:gap-12">{[['01', 'Buy less. Love longer.', 'We make pieces that earn their place, and stay there.'], ['02', 'Know who made it.', 'Every piece has a person and a process behind it.'], ['03', 'Leave things better.', 'We choose materials and partners with tomorrow in mind.']].map(([number, title, text]) => <article key={number} className="border-t border-[#c9c8bc] pt-4"><span className="serif text-[17px] text-[#8e765f]">{number}</span><h3 className="serif mt-4 text-[24px]">{title}</h3><p className="mt-2 text-[12px] leading-6 text-[#70746b]">{text}</p></article>)}</div></div></section>
    </main>
  )
}